name: Build Firmware Binary

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'

jobs:  
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Build firmware and output binary
        uses: esphome/build-action@v6
        with:
          yaml-file: stock_ticker_main.yaml