name: Build Firmware Binary

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'

jobs:  
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Build firmware and output binary
        uses: esphome/build-action@v6
        with:
          yaml-file: stock_ticker_main.yaml

      - name: Get short SHA
        run: 'echo "SHORT_SHA=${GITHUB_SHA: -7}" >> $GITHUB_ENV'

      - name: Create release with compiled OTA firmware file
        uses: softprops/action-gh-release@v2.3.2
        with:
          files: stock_ticker_display_main-esp32c3/stock_ticker_display_main-esp32c3.ota.bin
          tag_name: ${{ env.SHORT_SHA }}